spring:
  profiles:
    active: dev
server:
  port: 6001

#logback
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.hanzo: DEBUG
    com.alibaba.druid.pool.DruidDataSource: DEBUG
  file.name: ./logs/hanzo-demo-test.log