server:
  port: 6701
  servlet:
    session:
      timeout: 1800s

spring:
  profiles:
    active: dev

#logback
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.hanzo: DEBUG
    com.alibaba.druid.pool.DruidDataSource: DEBUG
  file.name: ./logs/${spring.application.name}.log

feign:
  httpclient:
    #让Feign使用apache httpClient做请求,而不是默认的urlconttion
    enabled: true
    #Feign的最大连接数
    max-connections: 200
    #Feign单个路径的最大连接数
    max-connections-per-route: 50
  hystrix:
    enabled: true
    #对请求与响应进行GZIP压缩，以减少通信过程中的性能损耗
  compression:
    request:
      enabled: true
    response:
      enabled: true

ribbon:
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询 默认
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
  ReadTimeout: 9000
  ConnectTimeout: 9000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  shareSecurityContext: true
  threadpool:
    default:
      coreSize: 20 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000