server:
  port: 6701

spring:
  #jackson转化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    visibility:
      GETTER: NONE
      SETTER: NONE
      FIELD: ANY # JSON序列化的key以属性名显示为主
    default-property-inclusion: non_null

#  main:
#    allow-bean-definition-overriding: true

  # mybatis 配置
  #mybatis:
  #mapper-locations: classpath:mapper/*.xml

#mybatis-plus配置
#mybatis-plus:
#  type-aliases-package: com.hanzo.system.entity
#  mapper-locations: classpath*:/mapper/*.xml
#  #  开启数据库驼峰转换
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: null #指定为null，否则再插入空值时会报"无效的列类型"错误
#  #关闭MyBatis Plus Banner打印
#  global-config:
#    banner: false


