server:
  port: 6301


Spring:
  #Mysql数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hanzo_cloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: Thy0528!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1  # 初始化大小
      min-idle: 5  # 最小
      max-active: 20  # 最大
      max-wait: 60000  # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      #filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
  #Redis数据库
  redis:
    database: 2
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password:
    lettuce:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 8
        min-idle: 0

  #jackson转化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# mybatis 配置
  #mybatis:
  #mapper-locations: classpath:mapper/*.xml

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.hanzo.auth.entity
  mapper-locations: classpath:mapper/*.xml
  #  开启数据库驼峰转换
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null #指定为null，否则再插入空值时会报"无效的列类型"错误
  #关闭MyBatis Plus Banner打印
  global-config:
    banner: false

#接口文档信息配置
swagger2:
  knife4j:
    apiBasePackage: com.hanzo.auth.controller
    enableSecurity: false
    title: 认证授权中心
    description: 授权中心-API文档
    version: 1.0
    contactName: thy
    contactUrl: http://blog.babehome.com
    contactEmail: 246965218@qq.com

#是否开启jwt
access_token:
  enable-jwt: true
  jwt-signing-key: hanzo>_<cloud

#开放路径
auth:
  center:
    anonUris: /auth/**,/swaggerList,/oauth/token,/oauth/check_token,/oauth/user/token,/users-anon/**,/smsVerify,/social/**

#一款快速集成oauth2 第三方登录的开源工具justAuth配置
justauth:
  enabled: true
  type:
    QQ:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://localhost:6301/social/callback/qq
      union-id: false
    GITHUB:
      client-id: xxxxx
      client-secret: xxxxxx
      redirect-uri: http://localhost:6301/social/callback/github
    WECHAT_OPEN:
      client-id: xxxxxxx
      client-secret: xxxxxxx
      redirect-uri: http://localhost:6301/social/callback/wechat
    WEIBO:
      client-id: xxxxx
      client-secret: xxxxxx
      redirect-uri: http://localhost:6301/social/callback/weibo
  cache:
    type: redis
    prefix: 'HANZO::CLOUD::SOCIAL::STATE::'
    timeout: 1h